name: flutter_ai_chat
description: "Flutter AI Chat Sample"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_ui_auth: ^3.0.0
  firebase_messaging: ^16.0.1
  flutter_ai_toolkit: ^0.10.0
  flutter_markdown: ^0.7.3+2
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  openai_dart: ^0.5.5
  future_builder_ex: ^5.0.0
  gap: ^3.0.1
  go_router: ^16.2.1
  shared_preferences: ^2.3.2
  split_view: ^3.2.1
  uuid: ^4.5.1
  camera: ^0.11.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43

flutter:
  uses-material-design: true
  assets:
    - assets/
