// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQEJj7i6mCptLCZe352eNr0C1olFqbz0',
    appId: '1:1017522654582:web:b8691d7d78b3d298633e57',
    messagingSenderId: '1017522654582',
    projectId: 'aegischat-d7bad',
    authDomain: 'aegischat-d7bad.firebaseapp.com',
    storageBucket: 'aegischat-d7bad.firebasestorage.app',
    measurementId: 'G-45EJRTB273',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXCGwnsFbUxl5AL3z8lIsiJeIPm483Tos',
    appId: '1:1017522654582:android:98f0c0c7620cb62b633e57',
    messagingSenderId: '1017522654582',
    projectId: 'aegischat-d7bad',
    storageBucket: 'aegischat-d7bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcYGxmfL_Xtwc0aRLrDQCoGOMOhCa-x4',
    appId: '1:1017522654582:ios:cab6ff1420587132633e57',
    messagingSenderId: '1017522654582',
    projectId: 'aegischat-d7bad',
    storageBucket: 'aegischat-d7bad.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcYGxmfL_Xtwc0aRLrDQCoGOMOhCa-x4',
    appId: '1:1017522654582:ios:cab6ff1420587132633e57',
    messagingSenderId: '1017522654582',
    projectId: 'aegischat-d7bad',
    storageBucket: 'aegischat-d7bad.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQEJj7i6mCptLCZe352eNr0C1olFqbz0',
    appId: '1:1017522654582:web:d641f45e98a1a38b633e57',
    messagingSenderId: '1017522654582',
    projectId: 'aegischat-d7bad',
    authDomain: 'aegischat-d7bad.firebaseapp.com',
    storageBucket: 'aegischat-d7bad.firebasestorage.app',
    measurementId: 'G-9KPKZ1VW17',
  );
}
